Feature/16 create and set routing add method to pollcontroller
pollmelo/backberry pull request #24
Opened 2023-01-27 13:16 UTC by GrafBunsen

closing #16

2023-01-29 18:28 UTC, martincodes-de requested changes

2023-01-29 18:28 UTC, martincodes-de commented on app/Http/Controllers/PollController.php
> +    public function create(Request $request): Response
Controller action create doesnt fulfills requirements. see ticket

2023-01-29 18:28 UTC, martincodes-de commented on tests/Feature/HttpTest.php
> +     * A basic feature test example.
edit or remove description

2023-01-29 18:28 UTC, martincodes-de commented on tests/Feature/HttpTest.php
> +    public function test_example(): void
rename method

2023-01-30 09:33 UTC, GrafBunsen commented on app/Http/Controllers/PollController.php
> +    public function create(Request $request): Response
done

2023-01-30 09:33 UTC, GrafBunsen commented on tests/Feature/HttpTest.php
> +     * A basic feature test example.
removed

2023-01-30 09:33 UTC, GrafBunsen commented on tests/Feature/HttpTest.php
> +    public function test_example(): void
renamed

2023-01-30 09:49 UTC, martincodes-de requested changes

2023-01-30 09:49 UTC, martincodes-de commented on app/Http/Controllers/PollController.php
> +        return response()->json($poll,status: 201);
```suggestion
        return response()->json($poll, status: 201);
```

2023-01-30 10:00 UTC, martincodes-de approved these changes

2023-01-30 10:00 UTC, merged