Feature/32 create endpoint to get all polls with votes
pollmelo/backberry pull request #36
Opened 2023-01-31 14:01 UTC by GrafBunsen

closing #32

2023-01-31 15:54 UTC, martincodes-de requested changes

2023-01-31 15:54 UTC, martincodes-de commented on app/Http/Controllers/PollController.php
> +        return response()->json($convertedPolls);
please before return, add empty line

2023-01-31 21:49 UTC, martincodes-de requested changes

2023-01-31 21:49 UTC, martincodes-de commented on app/Http/Controllers/PollController.php
> +                "endDate" => $poll->end_date,
to be consistent here as api, i would recommend snake case like `updated_at` and so on.

2023-01-31 21:49 UTC, martincodes-de commented on app/Http/Controllers/PollController.php
> +                "downvotes" => $downvotes,
would move up and downvotes before created_at and updated_at

2023-02-01 07:43 UTC, GrafBunsen commented on app/Http/Controllers/PollController.php
> +        return response()->json($convertedPolls);
done

2023-02-01 07:49 UTC, GrafBunsen commented on app/Http/Controllers/PollController.php
> +                "endDate" => $poll->end_date,
we use lower camel case in the rest of the API, don't we? so change update-at to updateAt?

2023-02-01 07:50 UTC, GrafBunsen commented on app/Http/Controllers/PollController.php
> +                "downvotes" => $downvotes,
done

2023-02-01 17:03 UTC, martincodes-de submitted a review, later dismissed

2023-02-01 19:11 UTC, GrafBunsen commented on app/Http/Controllers/PollController.php
> +                "endDate" => $poll->end_date,
changed to camel case

2023-02-01 19:17 UTC, martincodes-de requested changes

2023-02-01 19:17 UTC, martincodes-de commented on app/Http/Controllers/PollController.php
> +            $votes = Vote::where('poll_id', $poll->id)->get();
Please use $votes = $poll->votes() instead of a new query

2023-02-01 19:30 UTC, GrafBunsen commented on app/Http/Controllers/PollController.php
> +            $votes = Vote::where('poll_id', $poll->id)->get();
done

2023-02-01 19:34 UTC, martincodes-de approved these changes
Now lgtm

2023-02-01 19:39 UTC, merged