Create fake data for polls and votes
pollmelo/backberry pull request #38
Opened 2023-01-31 16:00 UTC by emsbe

This PR solves #37 and adds a vote and a poll factory. These factories describe the kind of data needed to create a poll and a vote. The data itself is created with FakePHP. 

With the seed command `ddev exec php artisan seed 20`, 20 polls and a random amount of votes for each poll are created.

2023-01-31 21:33 UTC, martincodes-de commented
We should decrease the textlength of polls -> name. It's too big imo. Maybe a variation with random length would be great.

2023-01-31 21:39 UTC, martincodes-de commented
We should also use some other correct dates in the future to have a bit more realistic dates. After some [research](https://fakerphp.github.io/formatters/date-and-time/#datetimebetween), you can use `fake()->dateTimeBetween(lowestRange, highestRange)` to create some in that range. I would use a range from -1 week from now to +8 weeks from now.

2023-01-31 21:44 UTC, martincodes-de requested changes

2023-01-31 21:44 UTC, martincodes-de commented on app/Console/Commands/Seed.php
> +            ->count($this->argument("amountOfPolls"))
To solve the static code analysis problem: cast the argument as integer like `(int)$this->argument('amountOfPolls')`

2023-02-03 09:10 UTC, martincodes-de approved these changes

2023-02-03 09:14 UTC, GrafBunsen approved these changes

2023-02-03 11:14 UTC, merged